# General settings

debug: false

logDirectory: logs

ticketUrlsCauseEmbed: false

quotedTicketsCauseEmbed: false

forbiddenTicketPrefix: '!'

requiredTicketPrefix: ''

embedDeletionEmoji: '🗑️'

maxSearchResults: 5

projects:
  - BDS
  - MC
  - MCD
  - MCD2
  - MCL
  - MCLG
  - MCPE
  - REALMS
  - WEB

request:
  invalidTicketEmoji: ⏸
  noLinkEmoji: ⛔
  warningLifetime: 5000
  waitingEmoji: ⌛

  invalidRequestJql: created > -24h

  suggestedEmoji:
    - ✅
    - ☑️
    - ❌
    - 💬

  ignorePrependResponseMessageEmoji: ✅
  ignoreResolutionEmoji: 💬

  resolveDelay: 10000
  progressMessageAddDelay: 10000
  prependResponseMessage: whenResolved
  prependResponseMessageInLog: false

  responseMessage: |-
    ```
    {{author}} {{url}}
    {{message}}

    ```
