name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - name: Check code style
      run: npm run lint --if-present
    - name: Compile to JavaScript
      run: npm run compile --if-present
      env:
        CI: true
        
    - name: Upload new libraries
      uses: urielsalis/rsync-deploy@v1.1
      env:
        DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_PORT: 22
        FOLDER: "build/install/arisa-kt/lib"
        ARGS: "-avh --delete"
        SERVER_IP: ${{ secrets.REMOTE_HOST }}
        USERNAME: ${{ secrets.REMOTE_USER }}
        SERVER_DESTINATION: /home/mojira-discord-bot/mojira-discord-bot
    - name: Upload new configuration
      uses: urielsalis/rsync-deploy@v1.1
      env:
        DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_PORT: 22
        FOLDER: "arisa.json"
        ARGS: "-avh --delete"
        SERVER_IP: ${{ secrets.REMOTE_HOST }}
        USERNAME: ${{ secrets.REMOTE_USER }}
        SERVER_DESTINATION: /home/mojira-discord-bot/mojira-discord-bot
    - name: Run internal deploy script
      uses: fifsky/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        user: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        command: |
          /usr/bin/screen -ls | /bin/grep Detached | /usr/bin/cut -d. -f1 | /usr/bin/awk '{print $1}' | /usr/bin/xargs /bin/kill
          sleep 1
          cd mojira-discord-bot
          /usr/bin/screen -d -m bash -c 'npm run bot; exec sh'
          
        args: "-tt"
